### model
model_name_or_path: ../checkpoints/base_models/InternVL3_5-8B-Pretrained-HF
#adapter_name_or_path: xxx
template: intern_vl
trust_remote_code: true

### export
#export_dir: xxx
export_size: 5
export_device: auto  # choices: [cpu, auto]
export_legacy_format: false